<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Data</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/darkly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About Us</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li>
  <a href="analysis.html">Analysis</a>
</li>
<li>
  <a href="https://github.com/YiSu3924/meteorite_landing.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Data</h1>

</div>


<p>The dataset used in this project was sourced from Kaggle, where it
was provided as a CSV file. You can explore or download the dataset
directly from Kaggle by visiting <a
href="https://www.kaggle.com/code/kinguistics/exploring-meteorite-landing-sites/input">this
link</a>.</p>
<div id="clean-data" class="section level1">
<h1>Clean data</h1>
<p>As part of the data cleaning, we standardized the column names by
converting them all to lowercase for consistency and ease of use in
future analysis. We then filtered the dataset to include only records
from the years 1970 to 2013, ensuring that the analysis focused on a
more relevant and manageable timeframe. Next, we identified and removed
the “fall” column since all its entries contained the same value. Rows
with missing latitude or longitude values were also excluded to maintain
the accuracy and reliability of geographic data. Additionally, we
enriched the dataset by creating a new “continent” column. This was
achieved by classifying each record based on its
<code>geo_location</code> attribute, which allows for more detailed
geographic insights in the analysis.</p>
<pre class="r"><code>meteorite_data &lt;- read.csv(&quot;data/meteorite-landings.csv&quot;)

meteorite_data &lt;- meteorite_data %&gt;% 
  clean_names() %&gt;%
  filter(year &gt;= 1970 &amp; year &lt;= 2013) %&gt;% 
  select(-fall)

meteorite_data_cleaned &lt;- meteorite_data %&gt;%
  filter(!is.na(reclat) &amp; !is.na(reclong)) %&gt;%
  filter(!is.na(mass) &amp; !is.na(year)) %&gt;%
  filter(mass &gt; 0)</code></pre>
</div>
<div id="glimpse-of-data" class="section level1">
<h1>Glimpse of data</h1>
<pre class="r"><code>meteorite_sf &lt;- st_as_sf(meteorite_data_cleaned, coords = c(&quot;reclong&quot;, &quot;reclat&quot;), crs = 4326, remove = FALSE)

continents &lt;- ne_countries(scale = &quot;medium&quot;, returnclass = &quot;sf&quot;) %&gt;%
  group_by(continent) %&gt;%
  summarise()

meteorite_data_with_continents &lt;- st_join(meteorite_sf, continents[&quot;continent&quot;], join = st_intersects)

meteorite_data_with_continents &lt;- meteorite_data_with_continents %&gt;%
  mutate(continent = replace_na(continent, &quot;Ocean&quot;))

head(meteorite_data_with_continents)</code></pre>
<pre><code>## Simple feature collection with 6 features and 10 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -99.9 ymin: 13.66033 xmax: 42.81667 ymax: 45.82133
## Geodetic CRS:  WGS 84
##               name    id nametype      recclass  mass year   reclat   reclong
## 1         Acapulco    10    Valid   Acapulcoite  1914 1976 16.88333 -99.90000
## 2 Aioun el Atrouss   423    Valid  Diogenite-pm  1000 1974 16.39806  -9.57028
## 3          Akyumak   433    Valid     Iron, IVA 50000 1981 39.91667  42.81667
## 4        Al Zarnkh   447    Valid           LL5   700 2001 13.66033  28.96000
## 5  Alby sur Chéran   458    Valid Eucrite-mmict   252 2002 45.82133   6.01533
## 6   Almahata Sitta 48915    Valid   Ureilite-an  3950 2008 20.74575  32.41275
##              geo_location     continent                  geometry
## 1 (16.883330, -99.900000) North America    POINT (-99.9 16.88333)
## 2  (16.398060, -9.570280)        Africa POINT (-9.57028 16.39806)
## 3  (39.916670, 42.816670)          Asia POINT (42.81667 39.91667)
## 4  (13.660330, 28.960000)        Africa    POINT (28.96 13.66033)
## 5   (45.821330, 6.015330)        Europe  POINT (6.01533 45.82133)
## 6  (20.745750, 32.412750)        Africa POINT (32.41275 20.74575)</code></pre>
<p>The dataset is a simple feature collection comprising 6 features and
10 fields. The fields include key attributes such as the name, id, mass,
year, latitude, and longitude of meteorite landings, along with a
derived continent column.</p>
</div>
<div id="statistics-of-variables" class="section level1">
<h1>Statistics of Variables</h1>
<pre class="r"><code>summary(meteorite_data_cleaned)</code></pre>
<pre><code>##      name                 id          nametype           recclass        
##  Length:35882       Min.   :    4   Length:35882       Length:35882      
##  Class :character   1st Qu.:10995   Class :character   Class :character  
##  Mode  :character   Median :22200   Mode  :character   Mode  :character  
##                     Mean   :25973                                        
##                     3rd Qu.:40586                                        
##                     Max.   :57458                                        
##       mass              year          reclat          reclong       
##  Min.   :      0   Min.   :1970   Min.   :-87.37   Min.   :-165.43  
##  1st Qu.:      6   1st Qu.:1987   1st Qu.:-76.72   1st Qu.:   0.00  
##  Median :     25   Median :1997   Median :-71.50   Median :  53.95  
##  Mean   :   1484   Mean   :1995   Mean   :-43.65   Mean   :  66.13  
##  3rd Qu.:    133   3rd Qu.:2003   3rd Qu.:  0.00   3rd Qu.: 157.22  
##  Max.   :4000000   Max.   :2013   Max.   : 81.17   Max.   : 178.20  
##  geo_location      
##  Length:35882      
##  Class :character  
##  Mode  :character  
##                    
##                    
## </code></pre>
<p>The dataset contains 35,882 entries. The mass variable ranges from 0
to 4,000,000 grams, with a mean of 1,484 grams and a median of 25 grams,
indicating significant skewness. The year variable spans from 1970 to
2013, with a median year of 1997. Latitude and longitude values reflect
global coverage, while geographic and meteorite classification details
enrich the dataset.</p>
</div>
<div id="distribution-of-mass" class="section level1">
<h1>Distribution of Mass</h1>
<pre class="r"><code>meteorite_data_cleaned %&gt;%
  ggplot(aes(x = mass)) +
  geom_histogram(binwidth = 0.05, fill = &quot;steelblue&quot;, color = &quot;black&quot;) +
  scale_x_log10() +
  labs(
    title = &quot;Distribution of Meteorite Mass&quot;,
    x = &quot;Mass (log scale)&quot;,
    y = &quot;Count&quot;
  )</code></pre>
<p><img src="data_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The mass distribution is heavily skewed due to the presence of
extremely large meteorites. To normalize this skew, the log
transformation of the mass was applied, resulting in a distribution
resembling a normal distribution. This transformation facilitates better
visualization and analysis.</p>
</div>
<div id="numbers-of-landings-through-year" class="section level1">
<h1>Numbers of landings through Year</h1>
<pre class="r"><code>meteorite_data_cleaned %&gt;%
  ggplot(aes(x = year)) +
  geom_bar(fill = &quot;coral&quot;, color = &quot;black&quot;) +
  labs(
    title = &quot;Meteorite Landings Over Time&quot;,
    x = &quot;Year&quot;,
    y = &quot;Number of Landings&quot;
  )</code></pre>
<p><img src="data_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Meteorite landings were distributed unevenly across the years, with a
noticeable increase in records toward the later part of the timeframe.
This could be attributed to improved detection and recording
technologies. A time-series plot provides insights into the frequency
trends over the years.</p>
</div>
<div id="final-dataset-description" class="section level1">
<h1>Final Dataset Description</h1>
<p><code>name</code>: The name of the meteorite landing.</p>
<p><code>id</code>: A unique identifier for each meteorite.</p>
<p><code>nametype</code>: The classification of the name type (e.g.,
“Valid”).</p>
<p><code>recclass</code>: The classification of the meteorite based on
its composition.</p>
<p><code>mass</code>: The mass of the meteorite in grams.</p>
<p><code>year</code>: The year the meteorite landed or was
discovered.</p>
<p><code>reclat</code>: The latitude coordinate of the meteorite landing
site.</p>
<p><code>reclong</code>: The longitude coordinate of the meteorite
landing site.</p>
<p><code>geo_location</code>: A formatted string combining the latitude
and longitude of the meteorite landing.</p>
<p><code>continent</code>: The continent where the meteorite landed,
derived from the latitude and longitude.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
